//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace homework8
{
    using System;
    using System.Collections.Generic;
    
    public partial class details
    {
        public int detailId { get; set; }
        public Nullable<int> goodsId { get; set; }
        public string goodsName { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<double> detailAoumt { get; set; }
        public Nullable<double> quantity { get; set; }
    }
}
